# Generated by Django 5.2 on 2025-04-30 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("org_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("tag_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="display name")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("proj_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.organization",
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ct_application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Story",
            fields=[
                ("story_id", models.AutoField(primary_key=True, serialize=False)),
                ("storyteller", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("content", models.TextField()),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.organization",
                    ),
                ),
                (
                    "proj_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.project",
                    ),
                ),
                (
                    "curator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ct_application.user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StoryTag",
            fields=[
                ("story_tag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "story_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.story",
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectTag",
            fields=[
                ("proj_tag_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "proj_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.project",
                    ),
                ),
                (
                    "tag_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.tag",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserLogin",
            fields=[
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="ct_application.user",
                    ),
                ),
                ("username", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="OrgUser",
            fields=[
                ("org_user_id", models.AutoField(primary_key=True, serialize=False)),
                ("access", models.CharField(max_length=20)),
                (
                    "org_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.organization",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ct_application.user",
                    ),
                ),
            ],
        ),
    ]
