# Generated by Django 5.2 on 2025-05-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ct_application",
            "0002_remove_story_org_id_tag_value_alter_customuser_email_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="story_id",
        ),
        migrations.AddField(
            model_name="story",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
