# Generated by Django 5.2 on 2025-05-09 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct_application", "0003_remove_story_story_id_story_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tag",
            name="tag_id",
        ),
        migrations.AddField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
