# Generated by Django 5.2 on 2025-05-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct_application", "0004_remove_tag_tag_id_tag_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="proj_id",
        ),
        migrations.RemoveField(
            model_name="storytag",
            name="story_tag_id",
        ),
        migrations.AddField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="storytag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
