# Generated by Django 5.2 on 2025-05-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ct_application", "0004_alter_userlogin_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30, verbose_name="display name")),
            ],
        ),
        migrations.AlterField(
            model_name="orguser",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="ct_application.user"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ct_application.user",
            ),
        ),
        migrations.AlterField(
            model_name="story",
            name="curator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ct_application.user",
            ),
        ),
        migrations.AlterField(
            model_name="userlogin",
            name="user_id",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="ct_application.user",
            ),
        ),
    ]
