# Generated by Django 5.2 on 2025-05-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ct_application",
            "0005_remove_project_proj_id_remove_storytag_story_tag_id_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="user_id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
