# Generated by Django 5.2 on 2025-05-13 03:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ct_application", "0006_remove_customuser_user_id_customuser_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="content",
            new_name="text_content",
        ),
        migrations.RemoveField(
            model_name="project",
            name="id",
        ),
        migrations.RemoveField(
            model_name="story",
            name="id",
        ),
        migrations.RemoveField(
            model_name="storytag",
            name="id",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="id",
        ),
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="position",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="customuser",
            name="profile",
            field=models.FileField(
                default="profile_pics/default.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="organization",
            name="profile",
            field=models.FileField(
                default="org_pics/default.jpg", upload_to="org_pics/"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="proj_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="story",
            name="audio_content",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="story",
            name="image_content",
            field=models.FileField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AddField(
            model_name="story",
            name="story_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="storytag",
            name="story_tag_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tag",
            name="tag_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
