# Generated by Django 5.2 on 2025-05-14 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ct_application",
            "0007_rename_content_story_text_content_remove_project_id_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="story",
            old_name="text_content",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="city",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="position",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="description",
        ),
        migrations.RemoveField(
            model_name="organization",
            name="profile",
        ),
        migrations.RemoveField(
            model_name="project",
            name="proj_id",
        ),
        migrations.RemoveField(
            model_name="story",
            name="audio_content",
        ),
        migrations.RemoveField(
            model_name="story",
            name="image_content",
        ),
        migrations.RemoveField(
            model_name="story",
            name="story_id",
        ),
        migrations.RemoveField(
            model_name="storytag",
            name="story_tag_id",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="required",
        ),
        migrations.RemoveField(
            model_name="tag",
            name="tag_id",
        ),
        migrations.AddField(
            model_name="project",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="story",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="storytag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AddField(
            model_name="tag",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
