# Generated by Django 5.2 on 2025-05-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ct_application", "0009_rename_org_id_orguser_org_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="required",
            field=models.BooleanField(),
        ),
    ]
