# Generated by Django 5.2.1 on 2025-05-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ct_application", "0010_alter_tag_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="story",
            name="transcription",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="profile",
            field=models.FileField(
                default="user_default.jpg", upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="profile",
            field=models.FileField(default="org_default.jpg", upload_to="org_pics/"),
        ),
    ]
