# Generated by Django 5.2.1 on 2025-05-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "ct_application",
            "0011_story_transcription_alter_customuser_profile_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="story",
            name="transcription",
        ),
        migrations.AddField(
            model_name="story",
            name="is_transcript",
            field=models.BooleanField(null=True),
        ),
    ]
