# Generated by Django 5.2.1 on 2025-05-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct_application", "0012_remove_story_transcription_story_is_transcript"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
