# Generated by Django 5.2.1 on 2025-05-25 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct_application", "0013_project_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="insight_json",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
